### ISSUE TITLE
Autogen.sh errors if one of gtk+ is not installed on build system.

### ISSUE THREAD

**Issue by tarakbumba** [assen-totin/mate-applet-streamer#5] opened 2015-12-30 17:28 UTC
When i tried to compile mate-applet-streamer from git clone or github release, autogen.sh throws error if i want to compile it using either gtk+2 or gtk+3 . It requires both gtk+3 and gtk+2 dependencies is installed on build system. So, without gtk+3 is installed compiling with gtk+2 is impossible. See [gist page](https://gist.github.com/tarakbumba/9be357d5101c0b8ee37d) for my compilation logs.

**Comment by assen-totin** [comment] 2015-12-30 21:59
This is not a bug. 

Actual builds should only happen from a released tarball, which has all the required autoconf macros in place. When using a release tarball, it is sufficient to only have on of the supported GTK versions and only one of the supported GStreamer versions. 

MATE is moving towards GTK3 (and has, in fact, fully functional builds with it), so all components should support both GTK2 and GTK3. To achieve this, the machine which is used to prepare the release tarballs must have both GTK2 and GTK3 development files installed.

**Closed as completed by assen-totin** 2015-12-30 21:59 UTC

**Comment by tarakbumba** [comment] 2015-12-31 00:32
> MATE is moving towards GTK3 (and has, in fact, fully functional builds with it), so all components should support both GTK2 and GTK3. To achieve this, the machine which is used to prepare the release tarballs must have both GTK2 and GTK3 development files installed.

Well, with all my respect i don't agree this. Please see configure.ac files in Mate; for example [mate-indicator-applet](https://github.com/mate-desktop/mate-indicator-applet/blob/master/configure.ac)

That package can be build with only one of gtk+ devel files is installed using .autgen.sh or autoreconf -vif

So, it should not be a necessity but it is your call after all. Thank you.

**Comment by assen-totin** [comment] 2015-12-31 12:59
The quoted configure.ac forces the builder to specify the GTK version using --with-gtk=... - if this is missing, it raises an error. This is not nice, as it requires the user to specify something even if it only has one version of it. My approach guarantees that everything will be autodetected and specifying manually the GTK version (or the GStreamer version) is only needed if you have more than one installed. I believe in automation and simple things, so it will be kept this way.
